@extends('layout.mainlayout')

@section('content')
<!-- MAY NEED TO REUSE ABOUT HEADING AS THE NAVRBAR DESIGN FAILS WHEN THE HEADER IS COMPLETELY REMOVED
MASTHEAD COMPLETELY LINKED TO IT ALL SO MUST BE INCLUDED SOMEHOW, COULD JUST MAKE ANOTHER FILE AND HEADER THAT BARELY DISPLAYS-->
<div class="container">
  <div class="row">
    <p>FUCK YOU NIGGA</p>
    <p>LOOK AT SITE PLANS.TXT</p>
  </div>
</div>

@endsection
